### ISSUE TITLE
Please add Linux support for the server

### ISSUE THREAD

**Issue by KRDucky** [Terence-D/GameInputCommandServer#33]
As Star Citizen will be coming to Linux, please add a Linux Server version for the GameInputCommandServer.

**Comment by Terence-D** [comment]
That's the plan, originally wanted it but had issues with the actual keypress sending.  Probably once finish converting the mobile app to iOS etc

**Comment by Terence-D** [comment]
Moving issue to the new project GICS: https://github.com/Terence-D/GamingInterfaceCommandServer/issues/5 

Migrating to a new Net Core platform, most of the app should be multi platform by default _except_ for the keypress part (which is the whole point of the app.  That issue will be my tracking of it.  

Edit: Also for now the UI for Linux will be console based, likely at least until Net 6 is a thing with the new UI toolkit.

**Comment by Terence-D** [comment]
@KRDucky just wanted to let you know that this long overdue request is finally completed.  It's bare bones but will be released in the next version, thank you for your patience.
